---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: run-tekton-orka
spec:
  taskRef:
    name: tekton-orka
  params:
    - name: orka-api-url
      value: http://10.10.10.100
    - name: base-image
      value: catalina-ssh-30G.img
    - name: ssh-username
      value: admin
    - name: ssh-password
      value: admin
    - name: script
      value: |
        #!/bin/sh

        set -ex

        mkdir -p out
        nvram -xp > out/nvram.xml
