---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: orka-teardown
spec:
  params:
    - name: orka-token-secret
      type: string
      default: orka-token
    - name: orka-token-secret-key
      type: string
      default: token
    - name: orka-vm-name-config
      type: string
      default: orka-vm-name
    - name: orka-vm-name-config-key
      type: string
      default: vm-name
  steps:
    - name: teardown
      image: sburtonmacstadium/tekton-orka
      env:
        - name: ORKA_API
          valueFrom:
            configMapKeyRef:
              name: orka-tekton-config
              key: ORKA_API
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.orka-token-secret)
              key: $(params.orka-token-secret-key)
        - name: VM_NAME
          valueFrom:
            configMapKeyRef:
              name: $(params.orka-vm-name-config)
              key: $(params.orka-vm-name-config-key)
      script: |
        #!/bin/sh
        set -x
        orka-cleanup
        kubectl delete secret $(params.orka-token-secret) --ignore-not-found
        kubectl delete configmap $(params.orka-vm-name-config) --ignore-not-found
