---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: orka-deploy
spec:
  params:
    - name: script
      type: string
    - name: copy-build
      type: string
      default: "true"
    - name: verbose
      type: string
      default: "false"
    - name: ssh-key
      type: string
      default: "false"
    - name: ssh-secret
      type: string
      default: orka-ssh-creds
    - name: ssh-username-key
      type: string
      default: username
    - name: ssh-password-key
      type: string
      default: password
    - name: orka-token-secret
      type: string
      default: orka-token
    - name: orka-token-secret-key
      type: string
      default: token
    - name: orka-vm-name-config
      type: string
      default: orka-vm-name
    - name: orka-vm-name-config-key
      type: string
      default: vm-name
  steps:
    - name: copy-script
      image: sburtonmacstadium/tekton-orka
      script: |
        #!/bin/sh
        SCRIPT=$(mktemp)
        # Safeguard against having to escape quotes / vars in script
        cat > $SCRIPT << 'EOF'
        $(params.script)
        EOF
        copy-script $SCRIPT
    - name: build
      image: sburtonmacstadium/tekton-orka
      env:
        - name: ORKA_API
          valueFrom:
            configMapKeyRef:
              name: orka-tekton-config
              key: ORKA_API
        - name: VERBOSE
          value: $(params.verbose)
        - name: COPY_BUILD
          value: $(params.copy-build)
        - name: SSH_USERNAME
          valueFrom:
            secretKeyRef:
              name: $(params.ssh-secret)
              key: $(params.ssh-username-key)
        - name: SSH_PASSFILE
          value: /etc/$(params.ssh-secret)/$(params.ssh-password-key)
        - name: SSH_KEY
          value: $(params.ssh-key)
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.orka-token-secret)
              key: $(params.orka-token-secret-key)
        - name: VM_NAME
          valueFrom:
            configMapKeyRef:
              name: $(params.orka-vm-name-config)
              key: $(params.orka-vm-name-config-key)
      volumeMounts:
        - name: ssh-creds
          readOnly: true
          mountPath: /etc/$(params.ssh-secret)
      script: |
        #!/bin/sh
        set -x
        orka-deploy
  volumes:
    - name: ssh-creds
      secret:
        secretName: $(params.ssh-secret)
        items:
          - key: $(params.ssh-password-key)
            path: $(params.ssh-password-key)
            mode: 0400
  workspaces:
    - name: orka
