---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: orka-init
spec:
  params:
    - name: orka-api-url
      type: string
      default: http://10.221.188.100
    - name: base-image
      type: string
    - name: cpu-count
      type: string
      default: "3"
    - name: vcpu-count
      type: string
      default: "3"
    - name: vnc-console
      type: string
      default: "true"
    - name: orka-creds-secret
      type: string
      default: orka-creds
    - name: orka-creds-email-key
      type: string
      default: email
    - name: orka-creds-password-key
      type: string
      default: password
    - name: orka-token-secret
      type: string
      default: orka-token
    - name: orka-token-secret-key
      type: string
      default: token
    - name: orka-vm-name-config
      type: string
      default: orka-vm-name
    - name: orka-vm-name-config-key
      type: string
      default: vm-name
  results:
    - name: vm-name
  steps:
    - name: init
      image: sburtonmacstadium/tekton-orka
      env:
        - name: ORKA_API
          value: $(params.orka-api-url)
        - name: BASE_IMAGE
          value: $(params.base-image)
        - name: CPU_COUNT
          value: $(params.cpu-count)
        - name: VCPU_COUNT
          value: $(params.vcpu-count)
        - name: VNC_CONSOLE
          value: $(params.vnc-console)
        - name: SVC_EMAIL
          valueFrom:
            secretKeyRef:
              name: $(params.orka-creds-secret)
              key: $(params.orka-creds-email-key)
        - name: SVC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(params.orka-creds-secret)
              key: $(params.orka-creds-password-key)
      script: |
        #!/bin/sh
        set -x
        orka-init
        if [ $? -ne 0 ]; then
          orka-cleanup
          exit 1
        fi
        TOKEN=/etc/orka-token
        VM_NAME=/etc/orka-vm-name
        if [ -f "$TOKEN" ] && [ -f "$VM_NAME" ]; then
          kubectl delete secret $(params.orka-token-secret) --ignore-not-found
          kubectl create secret generic $(params.orka-token-secret) \
            --from-file=$(params.orka-token-secret-key)=$TOKEN
          kubectl delete configmap $(params.orka-vm-name-config) --ignore-not-found
          kubectl create configmap $(params.orka-vm-name-config) \
            --from-file=$(params.orka-vm-name-config-key)=$VM_NAME
        else
          echo "fatal: could not create resources!"
          orka-cleanup
          exit 1
        fi
