---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: orka-full
spec:
  params:
    - name: orka-api-url
      type: string
      default: http://10.221.188.100
    - name: base-image
      type: string
    - name: verbose
      type: string
      default: "true"
    - name: script
      type: string
    - name: orka-creds-secret
      type: string
      default: orka-creds
    - name: orka-creds-email-key
      type: string
      default: email
    - name: orka-creds-password-key
      type: string
      default: password
    - name: orka-creds-license-key
      type: string
      default: licenseKey
    - name: ssh-username
      type: string
    - name: ssh-secret
      type: string
      default: orka-ssh-pw
    - name: ssh-secret-key
      type: string
      default: password
  results:
    - name: build-script
    - name: vm-name
  steps:
    - name: copy-script
      image: sburtonmacstadium/tekton-orka
      script: |
        #!/bin/sh
        SCRIPT=$(mktemp)
        # Safeguard against having to escape quotes / vars in script
        cat > $SCRIPT << 'EOF'
        $(params.script)
        EOF
        copy-script $SCRIPT
    - name: build
      image: sburtonmacstadium/tekton-orka
      env:
        - name: ORKA_API
          value: $(params.orka-api-url)
        - name: BASE_IMAGE
          value: $(params.base-image)
        - name: VERBOSE
          value: $(params.verbose)
        - name: SSH_USERNAME
          value: $(params.ssh-username)
        - name: SSH_PASSWORD
          value: /etc/$(params.ssh-secret)/$(params.ssh-secret-key)
        - name: SVC_EMAIL
          valueFrom:
            secretKeyRef:
              name: $(params.orka-creds-secret)
              key: $(params.orka-creds-email-key)
        - name: SVC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(params.orka-creds-secret)
              key: $(params.orka-creds-password-key)
        - name: LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.orka-creds-secret)
              key: $(params.orka-creds-license-key)
      volumeMounts:
        - name: ssh-creds
          readOnly: true
          mountPath: /etc/$(params.ssh-secret)
      command:
        - orka-full
      # script: |
      #   #!/bin/sh
      #   set -x
      #   ls -al /etc/orka-ssh-pw
      #   cat $SSH_PASSWORD
      #   # VM_NAME=$(cat /tekton/results/vm-name)
      #   # echo "Build script:"
      #   # cat $VM_NAME
      #   # echo "WOW" >> $(workspaces.orka.path)/wow.txt
      #   # tekton-orka
      #   # ls -al
      #   # cat /tekton/results/vm-name
      #   # ls -al $(workspaces.orka.path)
  volumes:
    - name: ssh-creds
      secret:
        secretName: $(params.ssh-secret)
  workspaces:
    - name: orka
