---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tekton-orka
spec:
  params:
    - name: orka-api-url
      type: string
      default: http://10.221.188.100
    - name: base-image
      type: string
    - name: ssh-username
      type: string
    - name: ssh-password
      type: string
    - name: script
      type: string
  results:
    - name: vm-config
  steps:
    - name: copy-script
      image: sburtonmacstadium/tekton-orka
      command:
        - /bin/sh
      args:
        - -c
        - set -ex && echo "$(params.script)" > script.sh
    - name: build
      image: sburtonmacstadium/tekton-orka
      env:
        - name: ORKA_API
          value: $(params.orka-api-url)
        - name: BASE_IMAGE
          value: $(params.base-image)
        - name: SSH_USERNAME
          value: $(params.ssh-username)
        - name: SSH_PASSWORD
          value: $(params.ssh-password)
        - name: SVC_EMAIL
          valueFrom:
            secretKeyRef:
              name: tekton-orka-creds
              key: email
        - name: SVC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tekton-orka-creds
              key: password
        - name: LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: tekton-orka-creds
              key: licenseKey
      command:
        - tekton-orka
      # script: |
      #   echo "$(params.script)" > script.sh
      #   tekton-orka
      #   pwd
      #   ls -al
      #   ls -al /tekton/results
      #   cat /tekton/results/vm-config
