---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: dump-disk-info
spec:
  taskRef:
    name: orka-full
  params:
    - name: orka-api-url
      value: http://10.10.10.100
    - name: base-image
      value: catalina-ssh-30G.img
    - name: ssh-username
      value: admin
    - name: script
      value: |
        DISK_INFO=$(mktemp)
        diskutil info / > $DISK_INFO
        cat $DISK_INFO
  workspaces:
    - name: orka
      emptyDir: {}
