---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: multi-stage-build
spec:
  workspaces:
    - name: shared-data
  tasks:
    - name: setup
      taskRef:
        name: orka-init
      params:
        - name: orka-api-url
          value: http://10.10.10.100
        - name: base-image
          # value: catalina-buildtools-90G.img
          value: catalina-ssh-30G.img
    - name: echo
      taskRef:
        name: orka-deploy
      params:
        - name: orka-api-url
          value: http://10.10.10.100
        - name: ssh-username
          value: admin
        - name: copy-build
          value: "false"
        - name: script
          value: |
            echo ok
      workspaces:
        - name: orka
          workspace: shared-data
    - name: ruby
      taskRef:
        name: orka-deploy
      params:
        - name: orka-api-url
          value: http://10.10.10.100
        - name: ssh-username
          value: admin
        - name: copy-build
          value: "false"
        - name: script
          value: |
            #!/usr/bin/env ruby
            puts "Hello macOS"
      workspaces:
        - name: orka
          workspace: shared-data
  finally:
    - name: cleanup
      taskRef:
        name: orka-teardown
      params:
        - name: orka-api-url
          value: http://10.10.10.100
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: run-multi-stage-build
spec:
  serviceAccountName: orka-svc
  pipelineRef:
    name: multi-stage-build
  workspaces:
    - name: shared-data
      emptyDir: {}
      # volumeClaimTemplate:
      #   spec:
      #     accessModes:
      #       - ReadWriteOnce
      #     resources:
      #       requests:
      #         storage: 1Gi
      #     storageClassName: manual
