---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: use-ssh-key
spec:
  taskRef:
    name: orka-full
  params:
    - name: orka-api-url
      value: http://10.10.10.100
    - name: base-image
      value: catalina-ssh-key-30G.img
    - name: ssh-username
      value: admin
    - name: ssh-secret
      value: orka-ssh-key
    - name: ssh-secret-key
      value: id_rsa
    - name: ssh-key
      value: "true"
    - name: verbose
      value: "true"
    - name: script
      value: |
        #!/usr/bin/env ruby
        puts "Hello macOS"
  workspaces:
    - name: orka
      emptyDir: {}
