name: tekton-orka-ci

on:
  push:
    paths:
      - .github/workflows/tekton-orka-ci.yaml
      - scripts/**
    branches:
      - master
      - releases/*

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create image tag
        run: |
          IMAGE_TAG=$(date '+%Y-%m-%d')-$(git rev-parse --short=8 HEAD)-${GITHUB_REF##*/}
          echo "::set-env name=IMAGE_TAG::${IMAGE_TAG}"
      - name: Deploy image
        run: |
          set -eux

          IMAGE=macstadium/orka-tekton-runner
          echo $IMAGE_TAG
          echo ${GITHUB_REF##*/}

          # docker build --tag $IMAGE .
          # docker push $IMAGE
