name: tekton-orka-ci

on:
  push:
    paths:
      - .github/workflows/tekton-orka-ci.yaml
      - scripts/**
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: deploy image
        run: |
          set -ex

          IMAGE=macstadium/orka-tekton-runner

          docker build --tag $IMAGE .
          docker push $IMAGE
