name: tekton-orka-ci

on:
  push:
    # paths:
    #   - '*'
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: deploy image
        run: |
          set -ex

          IMAGE=macstadium/tekton-orka

          docker build --tag $IMAGE .
          docker push $IMAGE
